apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend
  name: backend-svc
spec:
  selector:
    name: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP